spring:
  data:
    mongodb:
      database: Productdb11
      host: localhost
      port: 27017

server:
  port: 9093
logging:
  pattern:
    file: %d{yyyy-MM-dd } [%thread] %-5level %logger{36} - %msg%n
  file:
    path: = /
    name: log.txt
